
package es.ujaen.dae.localidadescercanas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocalidadesCercanasService", targetNamespace = "http://LocalidadesCercanas.dae.ujaen.es/", wsdlLocation = "http://localidades-dae2014.rhcloud.com:80/LocalidadesCercanas?wsdl")
public class LocalidadesCercanasService
    extends Service
{

    private final static URL LOCALIDADESCERCANASSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCALIDADESCERCANASSERVICE_EXCEPTION;
    private final static QName LOCALIDADESCERCANASSERVICE_QNAME = new QName("http://LocalidadesCercanas.dae.ujaen.es/", "LocalidadesCercanasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localidades-dae2014.rhcloud.com:80/LocalidadesCercanas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCALIDADESCERCANASSERVICE_WSDL_LOCATION = url;
        LOCALIDADESCERCANASSERVICE_EXCEPTION = e;
    }

    public LocalidadesCercanasService() {
        super(__getWsdlLocation(), LOCALIDADESCERCANASSERVICE_QNAME);
    }

    public LocalidadesCercanasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCALIDADESCERCANASSERVICE_QNAME, features);
    }

    public LocalidadesCercanasService(URL wsdlLocation) {
        super(wsdlLocation, LOCALIDADESCERCANASSERVICE_QNAME);
    }

    public LocalidadesCercanasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCALIDADESCERCANASSERVICE_QNAME, features);
    }

    public LocalidadesCercanasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocalidadesCercanasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalidadesCercanas
     */
    @WebEndpoint(name = "LocalidadesCercanasPort")
    public LocalidadesCercanas getLocalidadesCercanasPort() {
        return super.getPort(new QName("http://LocalidadesCercanas.dae.ujaen.es/", "LocalidadesCercanasPort"), LocalidadesCercanas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalidadesCercanas
     */
    @WebEndpoint(name = "LocalidadesCercanasPort")
    public LocalidadesCercanas getLocalidadesCercanasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://LocalidadesCercanas.dae.ujaen.es/", "LocalidadesCercanasPort"), LocalidadesCercanas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCALIDADESCERCANASSERVICE_EXCEPTION!= null) {
            throw LOCALIDADESCERCANASSERVICE_EXCEPTION;
        }
        return LOCALIDADESCERCANASSERVICE_WSDL_LOCATION;
    }

}
