
package es.ujaen.dae.localidadescercanas;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalidadesCercanas", targetNamespace = "http://LocalidadesCercanas.dae.ujaen.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalidadesCercanas {


    /**
     * 
     * @param ciudadOrigen
     * @param ciudades
     * @return
     *     returns java.util.List<es.ujaen.dae.localidadescercanas.Ciudad>
     * @throws CiudadInexistente_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ciudadesPorDistancia", targetNamespace = "http://LocalidadesCercanas.dae.ujaen.es/", className = "es.ujaen.dae.localidadescercanas.CiudadesPorDistancia")
    @ResponseWrapper(localName = "ciudadesPorDistanciaResponse", targetNamespace = "http://LocalidadesCercanas.dae.ujaen.es/", className = "es.ujaen.dae.localidadescercanas.CiudadesPorDistanciaResponse")
    @Action(input = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesPorDistanciaRequest", output = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesPorDistanciaResponse", fault = {
        @FaultAction(className = CiudadInexistente_Exception.class, value = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesPorDistancia/Fault/CiudadInexistente")
    })
    public List<Ciudad> ciudadesPorDistancia(
        @WebParam(name = "ciudadOrigen", targetNamespace = "")
        String ciudadOrigen,
        @WebParam(name = "ciudades", targetNamespace = "")
        List<String> ciudades)
        throws CiudadInexistente_Exception
    ;

    /**
     * 
     * @param ciudad
     * @param radio
     * @return
     *     returns java.util.List<es.ujaen.dae.localidadescercanas.Ciudad>
     * @throws CiudadInexistente_Exception
     * @throws RadioIncorrecto_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ciudadesCercanas", targetNamespace = "http://LocalidadesCercanas.dae.ujaen.es/", className = "es.ujaen.dae.localidadescercanas.CiudadesCercanas")
    @ResponseWrapper(localName = "ciudadesCercanasResponse", targetNamespace = "http://LocalidadesCercanas.dae.ujaen.es/", className = "es.ujaen.dae.localidadescercanas.CiudadesCercanasResponse")
    @Action(input = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesCercanasRequest", output = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesCercanasResponse", fault = {
        @FaultAction(className = CiudadInexistente_Exception.class, value = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesCercanas/Fault/CiudadInexistente"),
        @FaultAction(className = RadioIncorrecto_Exception.class, value = "http://LocalidadesCercanas.dae.ujaen.es/LocalidadesCercanas/ciudadesCercanas/Fault/RadioIncorrecto")
    })
    public List<Ciudad> ciudadesCercanas(
        @WebParam(name = "ciudad", targetNamespace = "")
        String ciudad,
        @WebParam(name = "radio", targetNamespace = "")
        float radio)
        throws CiudadInexistente_Exception, RadioIncorrecto_Exception
    ;

}
